version: "3.9"
services:
  taskapp:
    build: ./docker
    container_name: taskapp
    image: holoog/taskapp
    volumes:
      - ./:/var/www
    ports:
      - "8888:80"
    networks:
      - taskapp
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3309
      - DB_DATABASE=db-taskapp-01
      - DB_USERNAME=db-taskapp-user
      - DB_PASSWORD=secret101

  database:
    image: mysql
    container_name: taskapp-db
    restart: always
    ports:
      - "3309:3306"
    networks:
      - taskapp
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      - MYSQL_DATABASE=db-taskapp-01
      - MYSQL_USER=db-taskapp-user
      - MYSQL_PASSWORD=secret101
      - MYSQL_ROOT_PASSWORD=secret101

volumes:
  db-data:


networks:
  taskapp:
    driver: bridge
